services:
  api:
    ports:
      - "${API_HOST_BIND:-0.0.0.0}:${API_HOST_PORT:-20101}:${API_CONTAINER_PORT:-8080}"

  db:
    ports:
      - "${POSTGRES_HOST_BIND:-127.0.0.1}:${POSTGRES_HOST_PORT:-20132}:${POSTGRES_CONTAINER_PORT:-5432}"

