-- Generated by gen-orm | DB: postgresql | 2026-05-08T04:42:50.933Z

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  session_id VARCHAR(36) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions (user_id);

CREATE TABLE IF NOT EXISTS stage_progress (
  user_id VARCHAR(36) NOT NULL,
  stage_id INTEGER NOT NULL,
  stars INTEGER NOT NULL,
  cleared_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (user_id, stage_id)
);
COMMENT ON TABLE stage_progress IS 'PK is composite (user_id, stage_id) — best stars per stage';

CREATE TABLE IF NOT EXISTS client_meta (
  client_version VARCHAR(20) NOT NULL,
  meta_hash TEXT NOT NULL,
  protocol_version VARCHAR(20) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (client_version)
);

CREATE TABLE IF NOT EXISTS currency_logs (
  id BIGINT NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  transaction_id VARCHAR(36) NOT NULL,
  currency_type VARCHAR(32) NOT NULL,
  delta BIGINT NOT NULL,
  balance_before BIGINT NOT NULL,
  balance_after BIGINT NOT NULL,
  reason TEXT NOT NULL,
  correlation_id VARCHAR(36) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (id)
);
COMMENT ON TABLE currency_logs IS 'Append-only audit log — never UPDATE or DELETE';
CREATE INDEX IF NOT EXISTS idx_currency_logs_user_id ON currency_logs (user_id);

CREATE TABLE IF NOT EXISTS stamina_state (
  user_id VARCHAR(36) NOT NULL,
  current SMALLINT NOT NULL,
  last_recharged_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (user_id)
);
COMMENT ON TABLE stamina_state IS 'Lazy-evaluated stamina — current value at time of last write';

CREATE TABLE IF NOT EXISTS user_currency (
  user_id VARCHAR(36) NOT NULL,
  soft_amount BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id)
);
COMMENT ON TABLE user_currency IS 'Current soft currency balance per user';

CREATE TABLE IF NOT EXISTS inventory (
  user_id VARCHAR(36) NOT NULL,
  item_id INTEGER NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, item_id)
);
COMMENT ON TABLE inventory IS 'PK is composite (user_id, item_id)';

CREATE TABLE IF NOT EXISTS stage_best_records (
  user_id VARCHAR(36) NOT NULL,
  stage_id INTEGER NOT NULL,
  best_clear_time_ms BIGINT NOT NULL,
  best_score INTEGER NOT NULL,
  cleared_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (user_id, stage_id)
);
COMMENT ON TABLE stage_best_records IS 'PK is composite (user_id, stage_id) — best clear time + score per stage for ranking';

CREATE TABLE IF NOT EXISTS user_ranking_cache (
  user_id VARCHAR(36) NOT NULL,
  total_score BIGINT NOT NULL DEFAULT 0,
  stages_cleared INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (user_id)
);
COMMENT ON TABLE user_ranking_cache IS 'Aggregate ranking snapshot — rebuilt from stage_best_records on Redis cold start';

CREATE TABLE IF NOT EXISTS user_profiles (
  user_id VARCHAR(36) NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  avatar_id INTEGER NOT NULL DEFAULT 1,
  account_created_at TIMESTAMPTZ NOT NULL,
  last_login_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (user_id)
);
COMMENT ON TABLE user_profiles IS 'Game server user cache — populated on first login from JWT claims';

CREATE TABLE IF NOT EXISTS daily_challenge_progress (
  user_id VARCHAR(36) NOT NULL,
  challenge_date DATE NOT NULL,
  play_count INTEGER NOT NULL DEFAULT 0,
  completed BOOLEAN NOT NULL DEFAULT false,
  streak_days INTEGER NOT NULL DEFAULT 0,
  last_streak_date DATE,
  created_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (user_id, challenge_date)
);
COMMENT ON TABLE daily_challenge_progress IS 'Per-user per-day challenge tracking — play count and streak state';
CREATE INDEX IF NOT EXISTS idx_daily_challenge_user_id ON daily_challenge_progress (user_id);

CREATE TABLE IF NOT EXISTS player_settings (
  user_id VARCHAR(36) NOT NULL,
  bgm_enabled BOOLEAN NOT NULL DEFAULT true,
  sfx_enabled BOOLEAN NOT NULL DEFAULT true,
  haptics_enabled BOOLEAN NOT NULL DEFAULT true,
  notifications_enabled BOOLEAN NOT NULL DEFAULT true,
  language VARCHAR(8) NOT NULL DEFAULT 'EN',
  updated_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (user_id)
);
COMMENT ON TABLE player_settings IS 'Server-synced player preferences — authoritative if client-server sync is enabled';

CREATE TABLE IF NOT EXISTS action_logs (
  id BIGINT NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  action_type VARCHAR(64) NOT NULL,
  payload JSONB,
  correlation_id VARCHAR(36) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (id)
);
COMMENT ON TABLE action_logs IS 'Append-only general action audit log — never UPDATE or DELETE';
CREATE INDEX IF NOT EXISTS idx_action_logs_user_id ON action_logs (user_id);
CREATE INDEX IF NOT EXISTS idx_action_logs_action_type ON action_logs (action_type);
