-- Generated by gen-orm | DB: postgresql | 2026-05-06T04:58:55.546Z

CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  session_id VARCHAR(36) NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  active BOOLEAN NOT NULL DEFAULT true,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions (user_id);

CREATE TABLE IF NOT EXISTS stage_progress (
  user_id VARCHAR(36) NOT NULL,
  stage_id INTEGER NOT NULL,
  stars INTEGER NOT NULL,
  cleared_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (user_id, stage_id)
);
COMMENT ON TABLE stage_progress IS 'PK is composite (user_id, stage_id)';

CREATE TABLE IF NOT EXISTS client_meta (
  client_version VARCHAR(20) NOT NULL,
  meta_hash TEXT NOT NULL,
  protocol_version VARCHAR(20) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (client_version)
);

CREATE TABLE IF NOT EXISTS currency_logs (
  id BIGINT NOT NULL,
  user_id VARCHAR(36) NOT NULL,
  transaction_id VARCHAR(36) NOT NULL,
  currency_type VARCHAR(32) NOT NULL,
  delta BIGINT NOT NULL,
  balance_before BIGINT NOT NULL,
  balance_after BIGINT NOT NULL,
  reason TEXT NOT NULL,
  correlation_id VARCHAR(36) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  PRIMARY KEY (id)
);
COMMENT ON TABLE currency_logs IS 'Append-only audit log — never UPDATE or DELETE';
CREATE INDEX IF NOT EXISTS idx_currency_logs_user_id ON currency_logs (user_id);
